import 'package:carousel_slider/carousel_slider.dart';
import 'product_model.dart';

CarouselController carouselController = CarouselController();

List viewCategory = [
  {
    'id': 1,
    'name': 'All',
  },
  {
    'id': 2,
    'name': 'Fiction',
  },
  {
    'id': 3,
    'name': 'Psychology',
  },
  {
    'id': 4,
    'name': 'Finance',
  },
  {
    'id': 5,
    'name': 'Self-Help',
  },
];
// List category = [
//   {
//     'id': 1,
//     'name': 'Fiction',
//     'img': '🍕',
//   },
//   {
//     'id': 2,
//     'name': 'Psychology',
//     'img': '🍔',
//   },
//   {
//     'id': 3,
//     'name': 'Finance',
//     'img': '☕️',
//   },
//   {
//     'id': 4,
//     'name': 'Selp-Help Books',
//     'img': '🍦',
//   },
// ];

// List allProducts = [
//   Products(
//     id: 2,
//     name: 'Brain Connections',
//     category: 'Psychology',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/p1.png',
//     quantity: 1,
//     price: 329,
//   ),
//   Products(
//     id: 3,
//     name: 'Public Finance',
//     category: '️Finance',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/ff1.png',
//     quantity: 1,
//     price: 59,
//   ),
//   Products(
//     id: 4,
//     name: 'Subtle Art',
//     category: 'Self-Help',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/s1.png',
//     quantity: 1,
//     price: 129,
//   ),
//   Products(
//     id: 1,
//     name: 'Out Last Summer',
//     category: 'Fiction',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/fiction/f1.png',
//     quantity: 1,
//     price: 459,
//   ),
//   Products(
//     id: 2,
//     name: 'Creative Brain',
//     category: 'Psychology',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/p2.png',
//     quantity: 1,
//     price: 659,
//   ),
//   Products(
//     id: 4,
//     name: 'Inner Healing',
//     category: 'Self-Help',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/s2.png',
//     quantity: 1,
//     price: 259,
//   ),
//   Products(
//     id: 3,
//     name: 'Power of Invest',
//     category: 'Finance',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/ff2.png',
//     quantity: 1,
//     price: 69,
//   ),
//   Products(
//     id: 1,
//     name: 'The Secrets',
//     category: 'fiction',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/fiction/f2.png',
//     quantity: 1,
//     price: 699,
//   ),
//   Products(
//     id: 2,
//     name: 'The Human Brain',
//     category: 'Psychology',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/p3.png',
//     quantity: 1,
//     price: 269,
//   ),
//   Products(
//     id: 3,
//     name: 'Corporate',
//     category: 'Finance',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/ff3.png',
//     quantity: 1,
//     price: 69,
//   ),
//   Products(
//     id: 4,
//     name: 'Zen',
//     category: 'Self-Help',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/s3.png',
//     quantity: 1,
//     price: 29,
//   ),
//   Products(
//     id: 1,
//     name: 'Mastermind',
//     category: 'Fiction',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/fiction/f3.png',
//     quantity: 1,
//     price: 369,
//   ),
//   Products(
//     id: 1,
//     name: 'Ink & Stars',
//     category: 'Fiction',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/fiction/f4.png',
//     quantity: 1,
//     price: 569,
//   ),
//   Products(
//     id: 4,
//     name: 'Anxity',
//     category: 'Self-Help',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/s4.png',
//     quantity: 1,
//     price: 69,
//   ),
//   Products(
//     id: 3,
//     name: 'More Money',
//     category: 'Finance',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/ff5.png',
//     quantity: 1,
//     price: 99,
//   ),
//   Products(
//     id: 1,
//     name: 'The Garden',
//     category: 'Fiction',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/fiction/f5.png',
//     quantity: 1,
//     price: 999,
//   ),
//   Products(
//     id: 2,
//     name: 'Human Brain',
//     category: 'Psychology',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/p4.png',
//     quantity: 1,
//     price: 369,
//   ),
//   Products(
//     id: 4,
//     name: 'Power',
//     category: 'Self-Help',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/s5.png',
//     quantity: 1,
//     price: 69,
//   ),
//   Products(
//     id: 1,
//     name: '''Dragon's mother''',
//     category: 'Fiction',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/fiction/f6.png',
//     quantity: 1,
//     price: 859,
//   ),
//   Products(
//     id: 3,
//     name: 'Shallow',
//     category: 'Finance',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/ff6.png',
//     quantity: 1,
//     price: 19,
//   ),
//   Products(
//     id: 4,
//     name: 'Alchemist',
//     category: 'Self-Help',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/s6.png',
//     quantity: 1,
//     price: 99,
//   ),
//   Products(
//     id: 2,
//     name: 'Typography',
//     category: 'Psychology',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/p5.png',
//     quantity: 1,
//     price: 159,
//   ),
//   Products(
//     id: 2,
//     name: 'Element Spritives',
//     category: 'Psychology',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/p6.png',
//     quantity: 1,
//     price: 789,
//   ),
//   Products(
//     id: 3,
//     name: 'Black freedom',
//     category: 'Finance',
//     description: 'This Book is a good book to read with it.',
//     image: 'assets/images/stocks/ff4.png',
//     quantity: 1,
//     price: 79,
//   ),
// ];
