// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKyx6gS6do74LMpMGqjSmSBk94i70vX8',
    appId: '1:455157597091:web:04bd5294de83a056065016',
    messagingSenderId: '455157597091',
    projectId: 'test-1-flutter',
    authDomain: 'test-1-flutter.firebaseapp.com',
    storageBucket: 'test-1-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFTkwR4-ctJ2ICaVDwHVKQ_L1aZC1zso',
    appId: '1:455157597091:android:8ce8970487fe5f94065016',
    messagingSenderId: '455157597091',
    projectId: 'test-1-flutter',
    storageBucket: 'test-1-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaiXhhlN3U-bTKiHgy3r6o0YTI5qpmVQ',
    appId: '1:455157597091:ios:8c5185f3eb535979065016',
    messagingSenderId: '455157597091',
    projectId: 'test-1-flutter',
    storageBucket: 'test-1-flutter.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaiXhhlN3U-bTKiHgy3r6o0YTI5qpmVQ',
    appId: '1:455157597091:ios:ec5620ee2e7d57b3065016',
    messagingSenderId: '455157597091',
    projectId: 'test-1-flutter',
    storageBucket: 'test-1-flutter.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
